version: "3.9"
   
services:
  kibana:
    image: 'kibana:7.13.4'
    environment:
      - elasticsearch.hosts=http://elasticsearch:9200
    ports:
      - '5601:5601'
    depends_on:
      - elasticsearch
  elasticsearch:
    image: 'elasticsearch:7.13.4'
    environment:
        - discovery.type=single-node
    ports:
        - '9200:9200'
        - '9300:9300'
    volumes:
        - 'elasticsearch:/usr/share/elasticsearch/data'
  db:
    image: postgres
    ports:
      - 5433:5432
    volumes:
      - django-pgsql:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: 
      dockerfile: Dockerfile
      context: .
      target: base
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db

volumes:
  django-pgsql:
    driver: local
  elasticsearch:
    driver: local