# Generated by Django 3.2.6 on 2022-05-13 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
